name: cr
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - ca-certificates=2022.4.26=h06a4308_0
  - certifi=2022.6.15=py39h06a4308_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - intel-openmp=2022.0.1=h06a4308_3633
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - mkl=2022.0.1=h06a4308_117
  - ncurses=6.3=h7f8727e_2
  - openssl=1.1.1p=h5eee18b_0
  - pip=21.2.4=py39h06a4308_0
  - python=3.9.12=h12debd9_1
  - pytorch=1.12.0=py3.9_cuda11.3_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - readline=8.1.2=h7f8727e_1
  - setuptools=61.2.0=py39h06a4308_0
  - sqlite=3.38.5=hc218d9a_0
  - tk=8.6.12=h1ccaba5_0
  - typing_extensions=4.1.1=pyh06a4308_0
  - tzdata=2022a=hda174b7_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.12=h7f8727e_2
  - pip:
    - absl-py==1.1.0
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.0.5
    - astunparse==1.6.3
    - attrs==21.4.0
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.1
    - cachetools==5.2.0
    - cffi==1.15.1
    - charset-normalizer==2.1.0
    - cycler==0.11.0
    - debugpy==1.6.0
    - decorator==5.1.1
    - deepctr-torch==0.2.8
    - defusedxml==0.7.1
    - emoji==0.6.0
    - entrypoints==0.4
    - executing==0.8.3
    - fastjsonschema==2.15.3
    - filelock==3.7.1
    - flatbuffers==1.12
    - fonttools==4.33.3
    - gast==0.4.0
    - google-auth==2.9.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.47.0
    - h5py==3.7.0
    - huggingface-hub==0.8.1
    - idna==3.3
    - importlib-metadata==4.12.0
    - ipykernel==6.15.0
    - ipython==7.25.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.1
    - jedi==0.18.1
    - jinja2==3.1.2
    - joblib==1.1.0
    - jsonschema==4.6.1
    - jupyter==1.0.0
    - jupyter-client==7.3.4
    - jupyter-console==6.4.4
    - jupyter-core==4.10.0
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==1.1.1
    - keras==2.9.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.3
    - libclang==14.0.1
    - markdown==3.3.7
    - markupsafe==2.1.1
    - matplotlib==3.5.2
    - matplotlib-inline==0.1.3
    - matplotlib-venn==0.11.7
    - mistune==0.8.4
    - mypy==0.961
    - mypy-extensions==0.4.3
    - mypyc-ipython==0.0.2
    - nbclient==0.6.5
    - nbconvert==6.5.0
    - nbformat==5.4.0
    - nest-asyncio==1.5.5
    - notebook==6.4.12
    - numpy==1.23.0
    - oauthlib==3.2.0
    - opt-einsum==3.3.0
    - packaging==21.3
    - pandas==1.4.3
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.1.1
    - praw==7.6.0
    - prawcore==2.3.0
    - prometheus-client==0.14.1
    - prompt-toolkit==3.0.30
    - protobuf==3.19.4
    - psutil==5.9.1
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.21
    - pygments==2.12.0
    - pyparsing==3.0.9
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - pytz==2022.1
    - pyyaml==6.0
    - pyzmq==23.2.0
    - qtconsole==5.3.1
    - qtpy==2.1.0
    - regex==2022.7.9
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - scikit-learn==1.1.1
    - scipy==1.8.1
    - seaborn==0.11.2
    - send2trash==1.8.0
    - six==1.16.0
    - soupsieve==2.3.2.post1
    - stack-data==0.3.0
    - superdebug==0.4.7
    - tensorboard==2.9.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.9.1
    - tensorflow-estimator==2.9.0
    - tensorflow-io-gcs-filesystem==0.26.0
    - termcolor==1.1.0
    - terminado==0.15.0
    - threadpoolctl==3.1.0
    - tinycss2==1.1.1
    - tokenizers==0.12.1
    - tomli==2.0.1
    - torch==1.12.0
    - tornado==6.1
    - tqdm==4.64.0
    - traitlets==5.3.0
    - transformers==4.20.1
    - typing-extensions==4.2.0
    - update-checker==0.18.0
    - urllib3==1.26.9
    - venn==0.1.3
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.3.3
    - werkzeug==2.1.2
    - widgetsnbextension==3.6.1
    - wrapt==1.14.1
    - zipp==3.8.0
prefix: /fs/clip-quiz/wanrong/conda/envs/cr
